src/test/java/BakhtiyarTest.java
habr.com - search function test
=> Baha - first commit

src/test/java/LidiyaTest.java
=> Li ma/test for bbc

src/test/java/KristinaDrobavaTest.java
Я исправила ошибки:
- поставила extends BaseTest;
- заменила на getDriver().get;
=> Kristina Drobava /my test

src/test/java/KristinaDrobavaTest.java
Я удалила в моем тесте driver.quit(), так как он не нужен в каждом тесте.
=> удаление driver.quit 

src/test/java/MariaTest.java
=> Add test duolingo

src/test/java/AKGroupBugHuntersTest.java
=> AKBugHuntersTrekTests

src/test/java/IgorShmakovTest.java
This test method search inventory of the Pick-n-Pull vehicle yard for Mercedes CLK vehicles
Get first vehicle found, open it page to get unique VIN (Vehicle Identification Number)
Decode VIN number using another website with database of VIN numbers
Verify that decoded data contains that VIN belongs to CLK model
=> add searchMercedesVinAndDecodeIt as first test.

src/test/java/OleMarinaTest.java
=> Test passed.

src/test/java/BorisSDellDotComTest.java, src/test/java/MariaTest.java, src/test/java/NataliiaTest.java, src/test/java/NinaTest.java, src/test/java/QaEndurancePeterSolovey.java, src/test/java/RomanTest.java
Ignored classes NinaTest & RomanTest.
commented out some tests in QaEndurancePeterSolovey class
=> Qa endurance peter solovey

src/test/java/KarinaKTest.java
=> Code updated with new data

src/test/resources/local.properties.TEMPLATE
Добавляю общий шаблон файла local.properties 
С Сергеем согласовано.
=> added deleted file

src/test/java/OlaTest.java
Please, approve my pull request
=> New test Ola

src/test/java/TatjanaS1GeonameTest.java
added 3  Tests for website geonames
=> added 3  Tests for website geonames

src/test/java/qa_java_beginners/Song99BottlesElenaNov686Test.java
class Song99BottlesElenaNov686Test added, 
testSongLyricsText() created
=> testSongLyricsText()

src/test/java/GroupBugHuntersTest.java
Added changes according to Sergey's comments and added Thread.sleep(2000) for test stability ;
=> Added changes according to Sergey's comments

src/test/java/qa_java_beginners/GalaKonHW12Song99BottlesTest.java
TC_12_01 Подтвердите, что в меню BROWSE LANGUAGES, подменю  J, пользователь может найти описание страницы, на которой перечеслены все программные языки, начинающиеся с буквы J,  отсортированные по названию
Шаги:
Открыть базовую страницу
Нажать на пункт меню BROWSE LANGUAGES
Нажать на подменю J
Подтвердить, что пользователь видит текст “All languages starting with the letter J are shown, sorted by Language.”
=> The test for first homework task created

src/test/java/qa_java_beginners/Song99BottlesJuliaChTest.java
TC_12_03
* Подтвердите, что в меню BROWSE LANGUAGES существует таблица с
* заголовками Language, Author, Date, Comments, Rate
* Шаги:
* 1. Открыть базовую страницу
* 2. Нажать на пункт меню BROWSE LANGUAGES
* 3. Подтвердить, что существует таблица с заголовками Language, Author, Date, Comments, Rate
=> Julia ch test2

src/test/java/qa_java_beginners/Song99BottlesKaterinaTerekhovaTest.java
=> Katerina terekhova_test song lyrics test

src/test/java/qa_java_beginners/Song99BottlesArailymLessonTest.java
Song99BottlesArailymLessonTest added 
testLyricsText() created
=> Song99BottlesArailymLessonTest added and testLyricsText()

src/test/java/qa_java_beginners/NataliyaUA99BottlesOfBeer1HW12Test.java
NataliyaUA99BottlesOfBeer1HW12Test.java created
testBrowseLanguageMenuTest added
=> NataliyaUATest99SongLyricsTest

src/test/java/qa_java_beginners/IgorKadach99BottlesOfBeerTest.java
IgorKadach99BottlesOfBeerTests for Homework 12
=> Igor Kadach tests for Homework 12

src/test/java/KarinaKTest.java, src/test/java/qa_java_beginners/EugeniaSrednitskayaTest.java, src/test/java/qa_java_beginners/GalaKonHW12Song99BottlesTest.java, src/test/java/qa_java_beginners/HW12AnnaAbgarTest.java, src/test/java/qa_java_beginners/HW12SabinaSaadTest.java
=> GalaKon HW12

src/test/java/qa_java_beginners/NataliyaUASong99BottlesLessonTest.java
Refactoring of Song99BottlesTest
=> Song99BottlesLessonTest refactored

src/test/java/IgorShmakovTest.java, src/test/java/KarinaKTest.java, src/test/java/SafronovaOlgaTest.java, src/test/java/qa_java_beginners/AnnaNezhevetsHW12T1Test.java, src/test/java/qa_java_beginners/GalaKonHW12Song99BottlesTest.java, src/test/java/qa_java_beginners/HW12KononirinIrinaShTest.java, src/test/java/qa_java_beginners/HW12SabinaSaadTest.java, src/test/java/qa_java_beginners/HW12Task_2_3_4_08AlimDuiLTest.java, src/test/java/qa_java_beginners/MaksPtHomeWork12Test.java, src/test/java/qa_java_beginners/ShurikDrink99BottlesOfBeerTest.java, src/test/java/qa_java_beginners/Song99BottlesDariaKozhTest.java, src/test/java/qa_java_beginners/Song99BottlesHelenVelTest.java, src/test/java/qa_java_beginners/Song99BottlesJuliaSabTest.java, src/test/java/qa_java_beginners/Song99BottlesLessonTest.java, src/test/java/qa_java_beginners/Song99BottlesMaksPtRefactoringTest.java, src/test/java/qa_java_beginners/Song99BottlesOlgaSTest.java, src/test/java/qa_java_beginners/Song99BottlesPatriotby07Test.java, src/test/java/qa_java_beginners/Song99BottlesServachakTest.java, src/test/java/qa_java_beginners/Song99BottlesSvetlanaG1011Test.java, src/test/java/qa_java_beginners/Song99BottlesVadimTrefTest.java
=> OlyaIlyukhina_testSong

src/test/java/qa_java_beginners/Song99BottlesOlgaIlyukhinaTest.java
Second attempt to commit tests
=> Song99BottlesOlgaIlyukhinaTest class added, 2 tests created, refactored

src/test/java/qa_java_beginners/Song99BottlesKarinaKTest.java
=> tests are ongoing

src/test/java/qa_java_beginners/ArailymAsarHW12_TC_12_01_Test.java, src/test/java/qa_java_beginners/Song99BottlesArailymLessonTest.java
=> Arailym asar hw12 tc 12 01 test

src/test/java/HeaderLogoIsClickableToHomepageTest.java, src/test/java/HeaderLogoIsViewedOnEachPageTest.java, src/test/resources/local.properties.TEMPLATE
Initial tests for US_102, TC 102.001-006, 011
=> Tests for US_102_002

src/test/java/DeleteBuild.java
https://trello.com/c/27rkW5Et/165-tc033-build-history-delete-build
https://trello.com/c/q6A7iBiT/44-us033-build-history-delete-build
https://trello.com/c/CJR7P1hT/185-at033delete-build-history
=> AT_033 | Build History > Delete build

src/test/java/BuildHistoryPageTest.java
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0kBm92hN&#x2F;143-tc030001-build-history-changes">TC_030.001 | Build History &gt; Changes</a></blockquote>
Also added test for TC_031.001 | Build History > Console Output
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7fIeFgyB&#x2F;154-tc031001-build-history-console-output">TC_031.001 | Build History &gt; Console Output</a></blockquote>
=> TC_030.001 & TC_031.001 | Build History > Changes & Console Output

src/test/java/KorotushakAddDescriptionTest.java
Create 2 automation  tests for US036 <Organization Folder > Add Description To The Folder>
=> Test for US036 Add folder description (TC036.001)

src/test/java/DeleteBuildTest.java, src/test/java/JulSabSingleCategoryUITest.java, src/test/java/runner/DeleteFolderTest.java
https://trello.com/c/pIkBcaDJ/402-at000000-tc-name
https://trello.com/c/TcfrKmeA/126-us016-folder-delete-a-folder
https://trello.com/c/t3x2L3ka/340-tc016-folder-delete-a-folder
=> AT__016 | Folder > Delete a folder

src/test/java/OrganizationFolderChangeAppearanceTest.java
=> test Organization Folder > change Appearance created + delete method

src/test/java/CreateMultibranchPipelineTest.java
Fixed priorities to prevent test fail.
=> ERR | New item > Create Multibranch Pipeline

src/test/java/OrganizationFolderTest.java
Create Organization Folder
Rename Organization Folder
Delete Organization Folder
=> Organization Folder

src/test/java/OrganizationFolderRenameTest.java
OBakatova/Added OrganizationFolderRenameTest
=> OBakatova/Added OrganizationFolderRenameTest

src/test/java/FreestyleProjectConfigurePageTest.java
=> TC_005a.001 - 005a.002 | Freestyle project > Configure: Check buttons

src/test/java/GroupBugHuntersBreadcrumbTest.java
https://trello.com/c/SC8hSCkl/489-tc124001-new-item-page-breadcrumb-ui
=> Add TC_124.001

src/test/java/CreateFolderTest.java, src/test/java/NewItemPageCategoryHoveringExperienceTest.java, src/test/java/RenameMultiConfigurationProjectTest.java
https://trello.com/c/tZJOru9Q/538-tc128-new-item-page-category-hovering-experience-ui
https://trello.com/c/KjBtoPil/49-us128-new-item-page-category-hovering-experience-ui
https://trello.com/c/UzA0xv5y/562-at128-new-item-page-category-hovering-experience-ui
=>  AT_128 New Item Page > Category Hovering Experience (UI)

src/test/java/OrganizationFolderTest.java
=> Add a new assert in @Test(priority = 3)

src/test/java/CreateFolderWithInvalidDataTest.java
=> AT_009.003 | Create folder with invalid data

src/test/java/TypeAnItemNameWithValidSpecialCharactersTest.java
=> AT_009.009 | Type an item name with valid special characters

src/test/java/CreateFreestyleProjectTestEP.java, src/test/java/DeleteBuildTest.java
https://trello.com/c/QhQJvcJQ/569-tc003-freestyle-project-rename
https://trello.com/c/l9LlXJqX/23-us003-freestyle-project-rename
https://trello.com/c/no9KzQk1/599-at000000-tc-name
=> AT_003 createFreestyleProjectRenametest

src/test/java/FolderCheckPreviewAndDeleteFolderTest.java
testDeleteFolderFromTheTopMenu created,
testCheckDescriptionInPreviewAndOnTheFolderPage refactored
=> TC_016.003/DeleteFolder

src/test/java/RenameMultibranchPipelineWithAddChangeDescription.java
https://trello.com/c/YeV91TrP/572-at050-multibranch-pipeline-configure-change-add-name-description
=> AT_050 | Multibranch Pipeline > Configure: Change /add name description

src/test/java/CreateFreestyleProjectTest.java
https://trello.com/c/90RH0YQU/595-at001008-tc001008-new-item-create-freestyle-project-valid-name-without-description
=> AT_001.008 | TC_001.008 | New item > Create Freestyle project > Valid name without description

src/test/java/BuildScheduleTest.java
**Negative scenario:**[https://trello.com/c/IFedP7Wi/629-tc024002-pipelineschedule-build-for-pipeline-negative](url)
_Preconditions:_ Log in into the system, create testing item pipeline and go to main dashboard
_Steps:_
- find needed pipeline on the table and go to the details page
- check if "build history" section contains a caption saying "no build"
_Expected result:_ caption "no build" in "build history" section
_Post-conditions:_ delete created testing item
-----------------------------------------------------------------------------------------------------------------------------
**Positive scenario:** [https://trello.com/c/3qfDgKwT/492-tc024001-pipelineschedule-build-for-pipeline-positive](url)
_Preconditions_: Log in into the system, create testing item pipeline and go to main …
=> AT_024.001 | Pipeline>Schedule build for Pipeline (Positive and negative)

src/test/java/CopyDataFromExistingItemIntoNewOneTest.java, src/test/java/RenamePipelineTest.java
https://trello.com/c/S7j1AjBS/596-at131001-new-item-page-additional-field-functionalitycopying-data-from-existing-item-into-the-new-one
=> Tests for US_131, TC_131.001

src/test/java/CopyDataFromExistingItemIntoNewOneTest.java
https://trello.com/c/6bgxhSwa/637-at131002-new-item-page-additional-field-functionalitycopying-data-from-existing-item-into-the-new-onenegative-scenario
=> Added tests for US_131, TC_131.002

src/test/java/DisableEnableOrganizationFolderEP.java
https://trello.com/c/JlDGohrS/37-us037-organization-folder-disable-enable-folder
https://trello.com/c/oTfWwbSt/640-tc037001-organization-folder-disable-folder
https://trello.com/c/WW8pT3sB/645-at037001-organization-folder-disable-folder
=> AT_037 DisableEnableOrganizationFolderEP

src/test/java/LogoConsistentStylingTest.java
https://trello.com/c/wmo9HEcx/168-tc102009-header-logo-consistent-stylingheader-logo-is-an-image
=> Added Test HeaderLogoIsImage for US_102, TC_TC_102.009

src/test/java/LogoConsistentStylingTest.java
https://trello.com/c/Py5ii8WV/664-at102010-header-logo-consistent-stylingheader-logo-image-extension-is-svg
=> Test Header logo image extension s svg for US_102, TC_102.010

src/test/java/CreateNewFreestyleProjectTest_TC001_038.java
**Pre-conditions:** run chrome driver and log in into Jenkins
**Steps:**
* click on "new item" and redirect to creating page
* input parameter ProjectName into name field
* click OK button
* do to dashboard
* find on jobs table needed item and click
**Parameters:**
1. ProjectName = newFreestyleProjectValidName
2. ProjectName = newFreestyleProjectInvalidName[]//*
3. ProjectName is null
4. ProjectName = new Freestyle Project
**Expected result:** current URL is a detail page of created item
**Post-conditions:** delete created test item, log out and quite
=> AT_001.022 | New item > Create Freestyle project

src/test/java/AddDescriptionToFolderEPTest.java, src/test/java/DeleteFolderTest.java
https://trello.com/c/C6dTQ2K2/692-tc011-folder-add-a-description-to-the-folder
https://trello.com/c/LojWr3HX/35-us011-folder-add-a-description-to-the-folder
https://trello.com/c/eGAICCgO/694-at011-adddescriptiontofoldertest
=> AT_011 AddDescriptionToFolderEPTest

src/test/java/FreestyleProjectInvalidDataTest.java
https://trello.com/c/hKevPjI6/606-at001009-tc001009-new-item-create-freestyle-project-invalid-name-without-descriptoin
=> AT_001.009 TC_001.009  InValid name without descriptoin

src/test/java/_FolderTest.java
move my tests to correct class
=> RF | _FolderTest > CreateFolderWithInvalidDataTest

src/test/java/_FreestyleTest.java
refactoring of tests by using TestUtils method
=> RF | _FreestyleTest> testFreestyleProjectEditDescription & testRenameFreestyleProject

src/test/java/_PipelineTest.java
add asserts.assertAll()
change locator
=> PipelineTest remove @Ignore in testBuildPipelineWithParameters()

src/test/java/_FreestyleTest.java, src/test/java/model/FreestyleConfigPage.java
Refactored tests: testConfigureSaveButton and testConfigureApplyButton.
Changed dependencies.
=> RF | _FreestyleTest refactored two tests.

src/test/java/runner/BaseModel.java, src/test/java/runner/BaseTest.java
BaseModel, BaseTest > added spaces before "return".
=> RF | BaseModel, BaseTest > added spaces before "return".

src/test/java/_HeaderTest.java, src/test/java/model/UserStatusPage.java, src/test/java/model/base/BaseHeaderFooterPage.java
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;k5zRR1Q8&#x2F;1121-rf-headertest-testcheckadminpage">RF | _HeaderTest &gt; testCheckAdminPage</a>
testCheckAdminPage() refactored to POM.
=> RF | _HeaderTest > testCheckAdminPage.

src/test/java/_FolderTest.java, src/test/java/model/FolderConfigPage.java, src/test/java/model/FolderPage.java
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ATwq29Pl&#x2F;1180-err-foldertest-testcheckdescriptioninpreviewandonthefolderpage">ERR | _FolderTest &gt; testCheckDescriptionInPreviewAndOnTheFolderPage</a>
Improved test stability.
=> ERR | _FolderTest > testCheckDescriptionInPreviewAndOnTheFolderPage.

src/test/java/model/FolderPage.java
Improved stability of method in case of different systemMessage length.
=> ERR | _FolderPage > small fix of method.

src/test/java/_MultiConfigurationProjectTest.java, src/test/java/model/MultiConfigurationProjectDefaultPage.java, src/test/java/model/MultiConfigurationProjectPage.java, src/test/java/model/MultiConfigurationProjectWorkspacePage.java
https://trello.com/c/3zpFJMoI/1230-at048001-multi-configuration-project-workspace-default
=> AT_048.001 | Multi-configuration project > Workspace (Default)

src/test/java/_MultiConfigurationProjectTest.java
ERR | MultiConfigurationProjectTest > testRenameMultiConfigurationProjectErrorEmptyName
Changed dependencies.
=> ERR | MultiConfigurationProjectTest

src/test/java/_ManageCredentialsTest.java, src/test/java/model/ManageCredentialsPage.java
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;u0o5ETnx&#x2F;1289-rf-managecredentialstest-testiconsizecsschangepositive-testiconsizechangepositive">RF | _ManageCredentialsTest &gt; testIconSizeCSSChangePositive, testIconSizeChangePositive</a>
Tests refactored to chain with asserts.
=> RF | _ManageCredentialsTest > testIconSizeCSSChangePositive, testIconSizeChangePositive

src/test/java/_NewItemTest.java, src/test/java/model/NewItemPage.java, src/test/java/runner/BaseModel.java
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tV6janfX&#x2F;1290-rf-newitemtest-testcheckitemlabelstyle-testcheckdescriptionstyle-testcheckiconavailabilityanddisplaying">RF | _NewItemTest &gt; testCheckItemLabelStyle; testCheckDescriptionStyle; testCheckIconAvailabilityAndDisplaying</a>
Tests refactored to chain.
=> RF | _NewItemTest > testCheckItemLabelStyle; testCheckDescriptionStyle; testCheckIconAvailabilityAndDisplaying
